### ISSUE TITLE
Error when adding base_url to _site.yml

### ISSUE THREAD

**Issue by mihagazvoda** [rstudio/distill#125]
I get this error when running `rmarkdown::render_site()` or knitting any `Rmd`: 
```
Error in node_append_content(x$node, value) : 
Expecting a single string value: [type=list; extent=0].
```
It happens even if I directly copy code from the example: 
```
name: "reproducible-finance-with-r"
title: "Reproducible Finance with R"
description: |
  Exploring reproducible finance with the R statistical 
  computing environment.
base_url: https://beta.rstudioconnect.com/content/3776/
navbar:
  logo: images/rstudio.png
  right:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
    - text: "Contributors"
      href: contributors.html
    - icon: fa fa-rss
      href: index.xml
output: distill::distill_article
```
