### ISSUE TITLE
Non-English characters

### ISSUE THREAD

**Issue by RafaelPeixotoM** [rstudio/distill#137]
Hi,
I'm new to Distill, and I'm trying to convert an R Markdown site of my own to Distill. But I getting this error:
pandoc.exe: Cannot decode byte '\xed': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Erro: pandoc document conversion failed with error 1 

Can't you use non-english characters on Distill' YALM?? It works fine on R Markdown.

**Comment by taraskaduk** [comment]
I've just tested this with the \xed character ("í"), as well as with Cyrillic characters, and the article knits without errors.
Since this issue has been open for almost 3 months, can one issue you no longer experience this problem, or have you abandoned distill altogether?

What version of Pandoc are you using?

**Comment by taraskaduk** [comment]
I think this issue can be closed?

**Comment by bobsan16** [comment]
i have same error:
```
pandoc.exe: Cannot decode byte '\xc8': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error: pandoc document conversion failed with error 1
Execution halted

Exited with status 1.

```
when have cyrilic characters in _site.yml 

```
name: "statiecon_"
title: "statiecon"
description: |
  statiecon
output_dir: "docs"
navbar:
  right:
    - text: "Home"
      href: index.html
    - text: "ИМБФГЖ"
      href: about.html
output: distill::distill_article
```
