### ISSUE TITLE
Question about keep_md

### ISSUE THREAD

**Issue by maelle** [rstudio/distill#147]
If in a post I use

```yaml
output:
  distill::distill_article:
    self_contained: false
    keep_md: true
```

and then knit, I get index.md in _site/, not in _posts/.

Is that the intended behaviour and if so why?
