### ISSUE TITLE
problem with knit/build since upgrading to 1.0

### ISSUE THREAD

**Issue by jenrichmond** [rstudio/distill#228]
hi team, 
I recently upgraded my R version (3.6.3) and needed to reinstall distill. Since then I have had trouble knitting my distill articles and building my site. When I knit individual Rmds or try to build my site, it gives me an error re $ and atomic vectors

![Screen Shot 2020-11-30 at 9 15 04 am](https://user-images.githubusercontent.com/40267093/100563860-9315b280-3313-11eb-8eb6-dd21be4d53eb.png)

The pages render just fine once I push them to git, but I can't preview them before doing that anymore. When uninstalled 1.0 and went back to 0.8,  the problem was fixed. 

thanks in advance for your help
Jen

PS my repo in case it is helpful https://github.com/jenrichmond/iamlearningr

**Comment by Maschette** [comment]
I checked and had the same problem as Jen working off her repo. 
I was building off a windows 10 machine. 

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252   
```

```
> rmarkdown::find_pandoc()
$version
[1] ‘2.7.2’

$dir
[1] "C:/Users/dale_mas/AppData/Local/Pandoc"

```

**Comment by cderv** [comment]
I also ran the example (thank you for sharing the website!). 

The backtrace is 
```r
Backtrace:
    x
 1. \-rmarkdown::render_site(encoding = "UTF-8")
 2.   \-generator$render(...) C:/Users/chris/Documents/DEV_R/rmarkdown/R/render_site.R:187:2
 3.     \-distill:::write_search_json(input, config)
 4.       \-base::lapply(...)
 5.         \-distill:::FUN(X[[i]], ...)
 6.           \-base::lapply(...)
 7.             \-distill:::FUN(X[[i]], ...)
 8.               \-distill:::as_utf8(author$name)
```

The issue relies in the `author$name`. All your articles do not currently follow the `distill_articles` format in yaml header. (as in https://rstudio.github.io/distill/basics.html#creating-an-article). Some of them (`errors.Rmd`, `data.Rmd`, ...) are using a `html_document` and the `author` field which goes with it. `distill_articles` expect something more complex for the author field, with a name filed. Ex: 
```yaml
---
title: "Distill for R Markdown"
description: | 
  Scientific and technical writing, native to the web
date: May 4, 2018
author:
  - first_name: "Yihui"
    last_name: "Xie"
    url: https://github.com/yihui
    affiliation: RStudio
    affiliation_url: https://www.rstudio.com
    orcid_id: 0000-0003-0645-5666
  - name: "JJ Allaire"
    url: https://github.com/jjallaire
    affiliation: RStudio
    affiliation_url: https://www.rstudio.com
  - name: "Rich Iannone"
    url: https://github.com/rich-iannone
    affiliation: RStudio
    affiliation_url: https://www.rstudio.com
bibliography: biblio.bib
output: distill::distill_article
---
```

You see the error with version 1 of distill and not previous ones because there is a new search feature (see first bullet of [NEWS](https://github.com/rstudio/distill/blob/master/NEWS.md#distill-v10-cran)). It requires a parsing of all the YAML header, and currently i believe distill expect that a distill website is made of `distill_article` document format. At least if there is a `author` field, it expects to have a subfield `name` as in the yaml example above.

BTW, I think it is best to use `distill_article`as document format for everything following the documentation. In a website the format is defined in `_site.yml` and you don't have to provide a `output:` field in the document. This will insure the theme is applied on all articles. Currently, some of your pages (like [`errors.html`](https://iamlearningr.netlify.app/errors.html)) do not have the theme of the distill website applied (like your [homepage](https://iamlearningr.netlify.app/index.html))

Hope it helps.
