### ISSUE TITLE
Create others listings like _posts

### ISSUE THREAD

**Issue by Felixmil** [rstudio/distill#241]
Hi, thank you for this package. I've been using a homemade framework based on [rmarkdown driven development](https://emilyriederer.netlify.app/post/rmarkdown-driven-development/) using  `rmarkdown::render_site()` but this simplify my whole workflow !

# Problem

In the website i'm working on, I want to organize posts in different folders, for example:

- `applications` containing all shiny apps related posts,
- `analysis` containing all data analysis reports posts,
- ...

On the website this would translate to one navbar link for each directory, each one of them would be a listing of the corresponding category.

# What I tried

Create a directory for each category:
```
- _applications/
  - sample_post_1/
    - sample_post_1.Rmd
- _analysis/
  - sample_post_2/
    - sample_post_2.Rmd
- site.yml
- index.Rmd
- applications.Rmd
- analysis.Rmd
```

`application.Rmd` and `analysis.Rmd` contains custom listings like below:

```
---
title: "Applications"
listing: applications
---
```

My `site.yml` contains the following:

```
...
  right:
    - text: "Home"
      href: index.html
    - text: "Applications"
      href: applications.html
    - text: "Analysis"
      href: analysis.html
...
```

# Error

When I build the website I get the following error:

```
Rendering: ./applications.Rmd
Erreur : The collection 'applications' does not have an article listing.
(try running render_site() to generate the listing)

Exited with status 1.
```

# Workaround

I was able to make this work by putting all posts in `_posts` directory and create manual listing like this:

```
- _posts/
  - sample_post_1/
    - sample_post_1.Rmd
  - sample_post_2/
    - sample_post_2.Rmd
```

in `applications.Rmd`

```
---
title: "Applications"
listing: 
  posts:
    - sample_post_1
---
```

The problem with that is that the manual list will be hard to maintain when a lot of `.Rmd` files exist in the `_posts` directory.

# Question

**Is there a way to create new directories that works like `_posts` directory works ?**

**Comment by jjallaire** [comment]
Thanks for this report, AFAICR this _should_ work the way you are using it. We will investigate and hopefully fix for the next release.

**Comment by jjallaire** [comment]
You have to register e.g. `applications` or `analysis` as a collection in the `_site.yml` file (along with any configuration settings in requires). For example:

```yaml
collections:
  posts:
    disqus: reproducible-finance-with-r
    share: [twitter, linkedin]
    subscribe: _subscribe.html
  analysis:
  applications: 
    categories: true
```

Note that the collection can just be empty as with `analysis:` above.

The `_posts` and `_articles` collections are automatically registered, but for others you need the explicit config (otherwise we'd have no way to know whether a given directory with an underscore was a collection or just something you want excluded from copying to the site dir). 

I'm glad you found your way to this as it's a reminder that this feature even exists! (I don't think it's documented anywhere, partly b/c even though I implemented it initially I wasn't confident that it was rock solid given that nearly the demos/testing/sites in the wild are using `_posts`). If you find that there are other things wrong let us know and we'll address, then perhaps w/ v1.3 we can fully document this feature.
