### ISSUE TITLE
Academicons not rendering in navbar

### ISSUE THREAD

**Issue by storopoli** [rstudio/distill#256]
I've created a custom CSS with `distill::create_theme()` and inserted the following
```css
/*-- Additional custom styles --*/
/* Add any additional CSS rules below                      */
@import url('https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css')
```

My `_site.yml` is the following:
```yml
name: "Estatistica com R"
theme: "theme.css"
output_dir: "docs"
navbar:
  logo:
    image: images/uninove.png
    href: https://www.uninove.br
  #source_url: https://github.com/storopoli/Estatistica
  search: true
  title: "Navbar Title"
  left:
    - text: "Tutoriais"
      menu:
        - text: "1. Comandos Básicos"
          href: 1-Comandos_Basicos.html
    - text: "Conteúdos Auxiliares"
      menu:
        - text: "Dados Faltantes"
          href: aux-Dados_Faltantes.html
        - text: "Coeficientes de uma Regressão"
          href: aux-Regressao_Coeficientes.html
        - text: "Tabelas para Publicação"
          href: aux-Tabelas_para_Publicacao.html
  right:
    - text: "Jose Storopoli, PhD"
    - icon: ai-google-scholar fa-lg
      href: https://scholar.google.com/citations?user=xGU7H1QAAAAJ&hl=en
    - icon: ai-orcid fa-lg
      href: https://orcid.org/0000-0002-0559-5176
    - icon: ai-lattes fa-lg
      href: http://lattes.cnpq.br/2281909649311607
    - icon: fa-github fa-lg
      href: http://github.com/storopoli
    - icon: fa-twitter fa-lg
      href: https://twitter.com/JoseStoropoli
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/in/storopoli/
output:
  distill::distill_article:
    toc: true
    toc_float: true
    highlight: tango
    highlight_downlit: true
creative_commons: CC BY
```

But I cannot render the Distill Website with the Academicons! Here is a screenshot after the `Build Site` was done:

<img width="1171" alt="Screen Shot 2020-12-22 at 13 26 23" src="https://user-images.githubusercontent.com/43353831/102910424-4d9f5d80-4459-11eb-8683-6301ef981c64.png">

**Comment by apreshill** [comment]
We support font awesome icons (https://fontawesome.com/icons?d=gallery), but not academicons (https://jpswalsh.github.io/academicons/). I think you'll need to download those locally and follow the instructions there.

**Comment by storopoli** [comment]
@apreshill Thank you for the prompt reply! Your webinars and tutorial helped me a lot (and still help me...). When you say

> I think you'll need to download those locally and follow the instructions there.

do you mean that I need to insert manually the Academicons' CSS?

If so, how can I insert a CSS like:
```html
<link rel="stylesheet" href="/path/to/folder/css/academicons.min.css"/>
```

in order for it to be rendered first or with a high priority in distill? I've tried inserting it everywhere. At the beginning of the index.Rmd, at the end, etc...

**Comment by cderv** [comment]
To complement previous answer, we don't support academicons out of the box in `icons:` field for navbar, because currently we check if icon passed starts with `fa ` (as fontawesome icons do) or otherwise we add the `fa ` prefix ourself, as we have built in support for fontawesome as @apreshill said. 

However it could work as a side effect because of the way iconset like academicons works (by identifying classes). You just need to pass the full academicons syntax and not expect us to add the correct prefix: 

> Call the icons in the same way as you would using Font Awesome, but replacing fa with ai.
<sup>From [jpswalsh.github.io/academicons](https://jpswalsh.github.io/academicons)</sup>

Try adding `ai ` before your icon names: 
```yaml
right:
    - text: "Jose Storopoli, PhD"
    - icon: ai ai-google-scholar fa-lg
      href: https://scholar.google.com/citations?user=xGU7H1QAAAAJ&hl=en
    - icon: ai ai-orcid fa-lg
      href: https://orcid.org/0000-0002-0559-5176
    - icon: ai ai-lattes fa-lg
      href: http://lattes.cnpq.br/2281909649311607
```

Also I think you are missing a `;` in your css

```css
/*-- Additional custom styles --*/
/* Add any additional CSS rules below                      */
@import url('https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css');
```

There will be `fa` class added to the icon too in the resulting HTML but I don't think it will prevent the icon to show (it does not when I test). We may try to support better other iconsets but that was not the plan for now as it is easy enough to add them. 

Related discussion and examples: https://github.com/rstudio/distill/issues/76
