### ISSUE TITLE
Includes content included twice in distill article

### ISSUE THREAD

**Issue by mattwarkentin** [rstudio/distill#279]
Hi,

When including additional HTML content via the `includes` YAML option, it appears as though the content is included twice over. Here is some code to help reproduce...
```yaml
# _site.yml
name: "test-website"
title: "Name"
description: |
  Placeholder
output_dir: "docs"
navbar:
  right:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
output:
  distill::distill_article:
    toc: true
    includes:
      before_body: include.html
      after_body: include.html
```

### include.html
```html
<p>Test</p>

```

And here is the result...
<img width="1280" alt="Screen Shot 2021-01-02 at 1 18 42 PM" src="https://user-images.githubusercontent.com/27825069/103463788-194f5b00-4cfd-11eb-9d34-cb3d28f979de.png">

**Comment by apreshill** [comment]
Hi there! Just so I understand, I would expect what you are seeing here since `include.html` seems to be inserted twice- once before and after the body, correct? Can you say more about what you would expect here?

```
output:
  distill::distill_article:
    toc: true
    includes:
      before_body: include.html <- first
      after_body: include.html    <- second
```
