### ISSUE TITLE
google_analytics in yaml for distill articles not working

### ISSUE THREAD

**Issue by ssp3nc3r** [rstudio/distill#293]
Following [this instruction](https://rstudio.github.io/distill/website.html#google-analytics) I've added a `google_analytics` to the yaml of my distill article and published on GitHub pages, 

````
---
title: "Data in Wonderland"
description: |
  Explores communication with data in various forms through seminal and cutting-edge ideas in writing, data analyses, and visualzation.
author:
  - name: Scott Spencer 
    url: https://ssp3nc3r.github.io
    affiliation: Columbia University
    affiliation_url: https://sps.columbia.edu/faculty/scott-spencer
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    base_format: distill::distill_article
    toc: true
    toc_depth: 2
    highlight: NULL
    self_contained: false
    css: styles.css
citation_url: https://ssp3nc3r.github.io/data_in_wonderland
repository_url: https://github.com/ssp3nc3r/data_in_wonderland
bibliography: references_reader.bib
google_analytics: UA-123500360-1
---
````

Looking in the html generated code, I did find the tracking id inserted into [the published distill article](https://ssp3nc3r.github.io/data_in_wonderland/) here:

```
<script type="text/json" id="radix-rmarkdown-metadata">
  {"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["title","description","author","date","output","citation_url","repository_url","bibliography","google_analytics"]}},"value":[{"type":"character","attributes":{},"value":["Data in Wonderland"]},{"type":"character","attributes":{},"value":["Explores communication with data in various forms through seminal and cutting-edge ideas in writing, data analyses, and visualzation.\n"]},{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","url","affiliation","affiliation_url"]}},"value":[{"type":"character","attributes":{},"value":["Scott Spencer"]},{"type":"character","attributes":{},"value":["https://ssp3nc3r.github.io"]},{"type":"character","attributes":{},"value":["Columbia University"]},{"type":"character","attributes":{},"value":["https://sps.columbia.edu/faculty/scott-spencer"]}]}]},{"type":"character","attributes":{},"value":["2021-01-16"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["bookdown::html_document2"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["base_format","toc","toc_depth","highlight","self_contained","css"]}},"value":[{"type":"character","attributes":{},"value":["distill::distill_article"]},{"type":"logical","attributes":{},"value":[true]},{"type":"integer","attributes":{},"value":[2]},{"type":"NULL"},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["styles.css"]}]}]},{"type":"character","attributes":{},"value":["https://ssp3nc3r.github.io/data_in_wonderland"]},{"type":"character","attributes":{},"value":["https://github.com/ssp3nc3r/data_in_wonderland"]},{"type":"character","attributes":{},"value":["references_reader.bib"]},{"type":"character","attributes":{},"value":["UA-123500360-1"]}]}
  </script>
```

but the analytics tag does not seem to be properly tracking. Is `google_analytics` inserted into distill article yaml intended to work or just in distill websites? If not, is there another way to properly add the tracking to the header of distill articles?
