### ISSUE TITLE
Render Math using KaTeX

### ISSUE THREAD

**Issue by chezui** [rstudio/distill#343]
Is there a way to use

```
pandoc --katex[=URL]
```

to render the site?

Thanks!

**Comment by cderv** [comment]
It won't answer directly but for reference I believe this is related to https://github.com/rstudio/rmarkdown/pull/1940 and associated issues. I think it could help provide support in other packages based on **rmarkdown** like **distill**

**Comment by cderv** [comment]
There is now a way if you use the **rmarkdown** current dev version as the mentioned PR has been merged. 

````yaml
output:
  distill::distill_article:
    math_method: katex
````
