### ISSUE TITLE
author key not showing in yaml when author specified in `create_post`

### ISSUE THREAD

**Issue by EllaKaye** [rstudio/distill#361]
Hello,

When I specify an author in the `create_post` function, the author key is missing in the resulting YAML, e.g. running

`create_post("EK post", author = "Ella Kaye")` 

creates the YAML

```
title: "EK post"
description: |
  A short description of the post.
Ella Kaye
date: 04-20-2021
output:
  distill::distill_article:
    self_contained: false
```

I think I have a fix for this and will submit it as a pull request.

(sorry, could figure out how do this as a `reprex` because `create_post` needs to be called in a distill website)

**Comment by cderv** [comment]
Hi @EllaKaye, 

which version of **distill** do you use ? Can you check ?

I use `1.2.4` last dev version and it works for me as expected when I run this function in a distill website
````yaml
---
title: "EK post"
description: |
  A short description of the post.
author: Ella Kaye
date: 2021-04-20
output:
  distill::distill_article:
    self_contained: false
---
````

This seems ok
https://github.com/rstudio/distill/blob/3ec93f17f52bc20bc6f15a8a01b8efd45ca06b0d/R/create.R#L160-L164

* if `author` is a character string then create `list(author = author)` and write in in YAML
``` r
yaml::as.yaml(list(author = "Ella Kaye"), indent.mapping.sequence = TRUE) 
#> [1] "author: Ella Kaye\n"
```

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
