### ISSUE TITLE
Error using create_post with author argument

### ISSUE THREAD

**Issue by glimmerphoenix** [rstudio/distill#365]
**Version info**
- {distill} v1.2
- R 4.0.5
- RStudio 1.4.1103

First, I start with a fresh Distill blog in a new RStudio project. Inside the blog project, when I execute in console this call to test the `create_post()` function:
```r
create_post("An example post", author = "Felipe Ortega")
```
Distill produces for the new post this header that fails to knit:
```yaml
---
title: "An example post"
description: |
  A short description of the post.
Felipe Ortega
date: 04-29-2021
output:
  distill::distill_article:
    self_contained: false
---
```
```
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: while scanning a simple key at line 4, column 1 could not find expected ':' at line 5, column 1
```
The problem is obvious, since there is a missing `author:` entry before the author info. Line 5 should be instead:
```
author: Felipe Ortega
```
I think there is a bug in `create_post()`, that is not producing a valid header when the `author` argument is provided.
