### ISSUE TITLE
Support for Submenus

### ISSUE THREAD

**Issue by tinyheero** [rstudio/distill#406]
In rmarkdown (at least 2.10+), there is support for submenus (https://github.com/rstudio/rmarkdown/pull/1426) in rmarkdown website. This doesn't seem to work in distill websites. For instance, consider the following `_site.yml`:

```yaml
name: "site"
navbar:
  title: "My Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
      menu:
        - text: "Sub_1"
          href: sub1.html
        - text: "Sub_2"
          menu:
            - text: "Sub_2_below"
              href: sub2.html
```

And the following `index.Rmd`:

```r
---
params:
  root_dir: NULL
title: "Distill Website"
description: |
  Scientific and technical writing, native to the web
output:
  distill::distill_article:
    toc: true
    code_folding: true
---

# Home Page
```

When we render this `Rscript --slave -e "rmarkdown::render('index.Rmd')"`, the index.html has this menu:

![distill_website_menu](https://user-images.githubusercontent.com/3268173/134940575-9c41eaf1-eca8-4f26-9872-fca5436cd949.png)

The "SUB_2" has no submenu. While if you change the `index.Rmd` to:

```r
---
params:
  root_dir: NULL
title: "Distill Website"
description: |
  Scientific and technical writing, native to the web
---

# Home Page
```

such that the output is no longer a distill article, but a rather rmarkdown article then we get this:

![rmarkdown_website_menu](https://user-images.githubusercontent.com/3268173/134940871-62268567-93f2-4905-a3b1-8457d7e38a9c.png).

Is it possible to get support for submenus in distill websites?
