### ISSUE TITLE
How to break line (e.g. in the Rmarkdown title and affiliation)?

### ISSUE THREAD

**Issue by fedenichetti** [rstudio/distill#467]
Is there an easy way, like adding some details to the theme.css file?
Thanks!

**Comment by hattesoul** [comment]
Hi,
at least for the **description**, author **name** and **affiliation** field you can try to use the `<br>` tag.
Unfortunately, I could not use it in the **title** field.
```
title: some<br>unbreakable title text
description: some<br>breakable<br>description text
author:
  - name: awesome<br>dude<span style="font-weight:normal !important">, part-time</span>
    affiliation: Institute of Awesomeness,<br>Awesome City,<br>Awesome Country
```
