### ISSUE TITLE
Italics in menu

### ISSUE THREAD

**Issue by silasprincipe** [rstudio/distill#474]
Hi!

I need to italicize some text of my menu. Is it possible to add some kind of markup in the YAML file to make text as italic?

Here is how my _yaml file looks like:

      menu:
        - text: "Species models"
        - text: "_Echinometra lucunter_" <<< this one needs to be in italic.
          href: eclu.html

But this is what I'm getting for now:

![image](https://user-images.githubusercontent.com/53846571/191281700-feb99618-5394-4a16-af44-bf73ebcccea6.png)

I appreciate any help you can give! Thanks again for creating distill.

**Comment by cderv** [comment]
Unfortunately, we don't resolve markdown syntax in this field. 

Maybe we can improve this without much trouble 🤔 

I think the current workaround is to use HTML content directly using `htmltools`

````
  menu:
    - text: "Species models"
    - text: !expr htmltools::em("Echinometra lucunter") 
      href: eclu.html
````

or use JS + CSS to tweak the menu by modifying the DOM

* `tweak.html`
````html
<script>
// Using JQuery available within distill website
$(function() {
  // tweak specific menu item
  // workaround for https://github.com/rstudio/distill/issues/474
  // - use any correct selector here
  item = $('div.nav-dropdown div.nav-dropdown-content a[href*="eclu.html"]')
  item.html("<em>"+item.text()+"</em>")
})
</script>
````

in `_site.yml`

````yaml
output:
  distill::distill_article:
    includes:
      after_body: tweak.html
````

Sorry for the inconvenience on that, I'll look at how improve this somehow to make more easy to use HTML directly. 🤔
