### ISSUE TITLE
Citation has incorrect format

### ISSUE THREAD

**Issue by carbonmetrics** [rstudio/distill#54]
This question was posted by me on [stackoverflow](https://stackoverflow.com/questions/52896242/citation-in-rmarkdown-incorrect-format), where it had 10 views and zero reactions:

I am trying out the new Radix for R Markdown.

The citations do not work very well for me. All titles have curly braces around them, and names with special characters are not shown correctly.

![screenshot_2018-10-19_18-57-03](https://user-images.githubusercontent.com/40055991/47297842-ef7b5380-d61e-11e8-8680-62f5849f1d36.png)

Here is an example:

```
---
title: "Untitled"
description: |
  A new article created using the Radix format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
bibliography: bib.bib
output: radix::radix_article
---
```

This is the citation [@Rockstrom2009]
Using the bib.bib file:

```
@article{Rockstrom2009,
archivePrefix = {arXiv},
arxivId = {10.1038/461472a},
author = {Rockstr{\"{o}}m, Johan and Steffen, Will and Noone, Kevin and Persson, {\AA}sa and Chapin, F. Stuart and Lambin, Eric and Lenton, Timothy M. and Scheffer, Marten and Folke, Carl and Schellnhuber, Hans Joachim and Nykvist, Bj{\"{o}}rn and de Wit, Cynthia A. and Hughes, Terry and van der Leeuw, Sander and Rodhe, Henning and S{\"{o}}rlin, Sverker and Snyder, Peter K. and Costanza, Robert and Svedin, Uno and Falkenmark, Malin and Karlberg, Louise and Corell, Robert W. and Fabry, Victoria J. and Hansen, James and Walker, Brian and Liverman, Diana and Richardson, Katherine and Crutzen, Paul and Foley, Jonathan},
doi = {10.5751/ES-03180-140232},
eprint = {461472a},
isbn = {0028-0836},
issn = {17083087},
journal = {Nature},
keywords = {Atmospheric aerosol loading,Biogeochemical nitrogen cycle,Biological diversity,Chemical pollution,Climate change,Earth,Global freshwater use,Land system change,Ocean acidification,Phosphorus cycle,Planetary boundaries,Stratospheric ozone,Sustainability,carrying capacity,climate change,ecology,nitrogen,phosphorus,planetary boundaries},
number = {24 September 2009},
pmid = {19779433},
primaryClass = {10.1038},
title = {{Planetary boundaries: Exploring the safe operating space for humanity}},
volume = {461},
year = {2009}
}
```
The bib file was exported through Mendeley 1.19.2 with LaTeX escape special characters = on. Using RStudio 1.2.1060 and R 3.4.4 on a Xubuntu 64 16.04 system.

How can I make these references show correctly? I have already tried switching off LaTeX special characters. The same biographic entries work fine in LaTeX.
