### ISSUE TITLE
Datacamp on distill/radix

### ISSUE THREAD

**Issue by henry090** [rstudio/distill#86]
Hi @jjallaire , I have a question regarding radix.

https://github.com/datacamp/tutorial offers **knitr utility to convert your static code chunks into an R editor where people can experiment.**

Their output is in the following form:

```
---
title: "Example Document"
author: "Your name here"
output:
  html_document:
    self_contained: false
---
```
But a radix article has the following format:

```
---
title: "Distill for R Markdown"
description: |
  Scientific and technical writing, native to the web
output:
  distill::distill_article:
    self_contained: false
---
```
Is it possible to use datacamp framework within radix article? 
```
output:
  html_document:
    self_contained: false
```

BTW, I tried but failed.
