### ISSUE TITLE
RSS feed questions

### ISSUE THREAD

**Issue by mattansb** [rstudio/distill#99]
1. Is it possible to create an RSS feed that is limited to some categories / labels / tags only?
2. Is it possible to have the RSS feed have the full content of the posts?

(Both these are required for R-Bloggers cross-posting...)

**Comment by Bisaloo** [comment]
Related: #33

**Comment by maelle** [comment]
I think it's possible these days.

See [this config](https://github.com/rstudio/ai-blog/blob/16af5437e1fb9ae11a0f7f67382853501375dfce/_site.yml#L30-L35)

```
rss:
  full_content: TRUE
  categories:
    - Packages/Releases
    - TensorFlow/Keras
    - R
```
